[workspace]
members = [
    "aoc2019",
    "aoc2024",
    "aoc2025",
    "utils",
]
exclude = [
    "template",
    "aoc2020",
    "aoc2021",
    "aoc2022",
    "aoc2023",
]
resolver = "2"

[profile.bench]
opt-level = 3
debug = 2
incremental = true

[profile.release]
opt-level = 3
debug = 2
incremental = true

[profile.test]
opt-level = 3
debug = 2
